name: SkyblockCore
version: '${version} (git: ${commitHash})'
author: Kopo942
main: net.motimaa.skyblockcore.SkyblockCore
api-version: 1.18
depend:
  - Citizens
  - LuckPerms
  - Vault
  - SuperiorSkyblock2
  - ProtocolLib
