name: SkyblockCore
version: '${version} (git: ${commitHash})'
author: AnttiMK
main: dev.kopo.skyblockcore.SkyblockCore
api-version: 1.19
depend:
  - Citizens
  - LuckPerms
  - Vault
  - SuperiorSkyblock2
  - ProtocolLib
